[package]
name = "s_america_yozhgoor"
version = "0.1.0"
authors = ["yozhgoor <yozhgoor@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candidate = { path = "../../candidate" }
chrono-tz = "0.5"
